 <head>
<link rel="stylesheet" type="text/css" href="../online-payments/public/js/jquery-ui/jquery-ui.theme.css">
<link rel="stylesheet" type="text/css" href="../online-payments/public/css/main.css">
<link rel="stylesheet" type="text/css" href="../online-payments/public/js/DataTables/css/jquery.dataTables.css">
<script type="text/JavaScript" src="../online-payments/public/js/jquery.js"></script>
<script type="text/JavaScript" src="../online-payments/public/js/jquery-ui/jquery-ui.min.js"></script>
<script type="text/JavaScript" src="../online-payments/public/js/DataTables/js/jquery.dataTables.js"></script>
</head>

<script>

function closeDialog() {
    $("#loading").dialog('close');
}

$(document).ready(function() {

    $('#import').button();
    $('#export').button();

    dataTable = $('#transactions').dataTable( {
        "processing": true,
        "serverSide": true,
        "ajax": {
            "url": "index.php/index/search-transactions-ajax",
            "type": "POST"
            },
        "columns":[
            {"data" : "General_Transaction_ID" },
            {"data" : "Program_Year" },
            {"data" : "Payment_Publication_Date" },
            {"data" : "Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name" },
            {"data" : "Covered_Recipient_Type" },
            {"data" : "Teaching_Hospital_ID" },
            {"data" : "Teaching_Hospital_Name" },
            {"data" : "Physician_Profile_ID" },
            {"data" : "Physician_First_Name" },
            {"data" : "Physician_Middle_Name" },
            {"data" : "Physician_Last_Name" },
            {"data" : "Physician_Name_Suffix" },
            {"data" : "Recipient_Primary_Business_Street_Address_Line1" },
            {"data" : "Recipient_Primary_Business_Street_Address_Line2", },
            {"data" : "Recipient_City" },
            {"data" : "Recipient_State" },
            {"data" : "Recipient_Zip_Code" },
            {"data" : "Recipient_Country" },
            {"data" : "Recipient_Province" },
            {"data" : "Recipient_Postal_Code" },
            {"data" : "Physician_Primary_Type" },
            {"data" : "Physician_Specialty" },
            {"data" : "Physician_License_State_code1" },
            {"data" : "Physician_License_State_code2", },
            {"data" : "Physician_License_State_code3" },
            {"data" : "Physician_License_State_code4" },
            {"data" : "Physician_License_State_code5" },
            {"data" : "Product_Indicator" },
            {"data" : "Name_of_Associated_Covered_Drug_or_Biological1" },
            {"data" : "Name_of_Associated_Covered_Drug_or_Biological2", },
            {"data" : "Name_of_Associated_Covered_Drug_or_Biological3" },
            {"data" : "Name_of_Associated_Covered_Drug_or_Biological4" },
            {"data" : "Name_of_Associated_Covered_Drug_or_Biological5" },
            {"data" : "NDC_of_Associated_Covered_Drug_or_Biological1" },
            {"data" : "NDC_of_Associated_Covered_Drug_or_Biological2", },
            {"data" : "NDC_of_Associated_Covered_Drug_or_Biological3" },
            {"data" : "NDC_of_Associated_Covered_Drug_or_Biological4" },
            {"data" : "NDC_of_Associated_Covered_Drug_or_Biological5" },
            {"data" : "Name_of_Associated_Covered_Device_or_Medical_Supply1" },
            {"data" : "Name_of_Associated_Covered_Device_or_Medical_Supply2", },
            {"data" : "Name_of_Associated_Covered_Device_or_Medical_Supply3" },
            {"data" : "Name_of_Associated_Covered_Device_or_Medical_Supply4" },
            {"data" : "Name_of_Associated_Covered_Device_or_Medical_Supply5" },
            {"data" : "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name" },
            {"data" : "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID" },
            {"data" : "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State" },
            {"data" : "Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country" },
            {"data" : "Dispute_Status_for_Publication" },
            {"data" : "Total_Amount_of_Payment_USDollars" },
            {"data" : "Date_of_Payment" },
            {"data" : "Number_of_Payments_Included_in_Total_Amount" },
            {"data" : "Form_of_Payment_or_Transfer_of_Value" },
            {"data" : "Nature_of_Payment_or_Transfer_of_Value" },
            {"data" : "City_of_Travel" },
            {"data" : "State_of_Travel" },
            {"data" : "Country_of_Travel" },
            {"data" : "Physician_Ownership_Indicator" },
            {"data" : "Third_Party_Payment_Recipient_Indicator" },
            {"data" : "Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value" },
            {"data" : "Charity_Indicator" },
            {"data" : "Third_Party_Equals_Covered_Recipient_Indicator" },
            {"data" : "Contextual_Information" },
            {"data" :"Delay_in_Publication_of_General_Payment_Indicator"}
            ],
        'columnDefs': 
            [ { orderable: false, targets: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61] }
            ]
        });
        $('#transactions_filter input').unbind();

       $('#transactions_filter input').bind('keyup', function(e) {
           if(e.keyCode == 13) {
            dataTable.fnFilter(this.value);   
        }
       });  
        $('#table-search').on( "click", function() {
            dataTable.fnFilter($( 'input[aria-controls="transactions"]' ).val());
        });

    $("#loading").dialog({
        hide: 'fade',
        show: 'fade',
        autoOpen: false,
        resizable: false,
        buttons: {},
        open: function(event, ui) { $(".ui-dialog-titlebar-close").hide(); }
    });

    $('#import').on( "click", function() {
        $.ajax({
                type: "POST",
                url: "index.php/index/import-ajax",
                data: {
                    address_id: 'hello'
                },
                async: false,
                // dataType: "JSON",
                beforeSend: function(){
                    //dont want any buttons..
                    $("#loading").dialog("option", "buttons", null);
                    $("#loading").dialog('open').html("<p class='center'>Your data is importing.. Please wait.<br>This may take a few minutes..<br><img src='../online-payments/public/images/loading.gif'></img></p>");
                },
                success: function (data) {
                    console.log('success');
                    $('#loading').dialog().html("<p class='center'>Data successfully imported.<br><br><button onclick='closeDialog();' id='close'>Close</button></p>");
                },
                error: function () {
                        console.log('error happened');
                    }
            });
        });

        $('#export').on( "click", function() {
            $.ajax({
                    type: "POST",
                    url: "index.php/index/download-xls",
                    data: {
                        term: $(':input[type=search]').val()
                    },
                    async: true,
                    beforeSend: function(){
                        $("#loading").dialog("option", "buttons", null);
                        $("#loading").dialog('open').html("<p class='center'>Preparing " + $('#transactions_info').html().split('of ')[1] + " for file download...<br><img src='../online-payments/public/images/loading.gif'></img></p>");
                    },
                    success: function (data) {
                        window.location.href = data;
                        $('#loading').dialog().html("<p class='center'>File downloaded<br><br><button onclick='closeDialog();' id='close'>Close</button></p>");
                    },
                    error: function () {
                            console.log('error happened');
                        }
                });
            });

             $( 'input[aria-controls="transactions"]' ).autocomplete({
                source: function (request, response) {
                    jQuery.get("index.php/index/autocomplete-ajax", {
                        query: request.term
                    }, function (data) {
                        data = JSON.parse(data);
                        response(data);
                    });
                },
                minLength: 3,
                select: function( event, ui ) {dataTable.fnFilter($( 'input[aria-controls="transactions"]' ).val());}
            });
    });

</script>

<div id="container">
    <h2 class="center">General Payment Data with Identifying Recipient Information</h2>
    <h3 class="center">Detailed Dataset 2013 Reporting Year</h3>

    <!-- search bar and buttons -->
    <div id='actions' class="center">
        <button id="import">Import Data</button>
        <button id="export">Export to .XLS</button>
    </div>
    <div id="table-container">
        <table id="transactions" class="display" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>General Transaction ID</th>
                        <th>Program Year</th>
                        <th>Payment Publication Date</th>
                        <th>Submitting Applicable Manufacturer or Applicable GPO Name</th>
                        <th>Covered Recipient Type</th>
                        <th>Teaching Hospital ID</th>
                        <th>Teaching Hospital Name</th>
                        <th>Physician Profile ID</th>
                        <th>Physician First Name</th>
                        <th>Physician Middle Name</th>
                        <th>Physician Last Name</th>
                        <th>Physician Name Suffix</th>
                        <th>Recipient Primary Business Street Address Line1</th>
                        <th>Recipient Primary Business Street Address Line2</th>
                        <th>Recipient City</th>
                        <th>Recipient State</th>
                        <th>Recipient Zip Code</th>
                        <th>Recipient Country</th>
                        <th>Recipient Province</th>
                        <th>Recipient Postal Code</th>
                        <th>Physician Primary Type</th>
                        <th>Physician Specialty</th>
                        <th>Physician License State code1</th>
                        <th>Physician License State code2</th>
                        <th>Physician License State code3</th>
                        <th>Physician License State code4</th>
                        <th>Physician License State code5</th>
                        <th>Product Indicator</th>
                        <th>Name of Associated Covered Drug or Biological1</th>
                        <th>Name of Associated Covered Drug or Biological2</th>
                        <th>Name of Associated Covered Drug or Biological3</th>
                        <th>Name of Associated Covered Drug or Biological4</th>
                        <th>Name of Associated Covered Drug or Biological5</th>
                        <th>NDC of Associated Covered Drug or Biological1</th>
                        <th>NDC of Associated Covered Drug or Biological2</th>
                        <th>NDC of Associated Covered Drug or Biological3</th>
                        <th>NDC of Associated Covered Drug or Biological4</th>
                        <th>NDC of Associated Covered Drug or Biological5</th>
                        <th>Name of Associated Covered Device or Medical Supply1</th>
                        <th>Name of Associated Covered Device or Medical Supply2</th>
                        <th>Name of Associated Covered Device or Medical Supply3</th>
                        <th>Name of Associated Covered Device or Medical Supply4</th>
                        <th>Name of Associated Covered Device or Medical Supply5</th>
                        <th>Applicable Manufacturer or Applicable GPO Making Payment Name</th>
                        <th>Applicable Manufacturer or Applicable GPO Making Payment ID</th>
                        <th>Applicable Manufacturer or Applicable GPO Making Payment State</th>
                        <th>Applicable Manufacturer or Applicable GPO Making Payment Country</th>
                        <th>Dispute Status for Publication</th>
                        <th>Total Amount of Payment USDollars</th>
                        <th>Date of Payment</th>
                        <th>Number of Payments Included in Total Amount</th>
                        <th>Form of Payment or Transfer of Value</th>
                        <th>Nature of Payment or Transfer of Value</th>
                        <th>City of Travel</th>
                        <th>State of Travel</th>
                        <th>Country of Travel</th>
                        <th>Physician Ownership Indicator</th>
                        <th>Third Party Payment Recipient Indicator</th>
                        <th>Name of Third Party Entity Receiving Payment or Transfer of Value</th>
                        <th>Charity Indicator</th>
                        <th>Third Party Equals Covered Recipient Indicator</th>
                        <th>Contextual Information</th>
                        <th>Delay in Publication of General Payment Indicator</th>
                    </tr>
                </thead>
        </table>
    </div>

    <div id="loading"></div>
</div>